/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2019. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.myapps.clouddbreference.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.IsIndex;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKey;

import java.util.Date;

/**
 * Definition of ObjectType UserSurvey.
 *
 * @since 2020-08-26
 */
public class UserSurvey extends CloudDBZoneObject {
    @PrimaryKey
    private Integer id;

    @NotNull
    @DefaultValue(stringValue = "test")
    private String fullName;

    @NotNull
    @DefaultValue(stringValue = "test")
    private String gender;

    @NotNull
    @DefaultValue(intValue = 18)
    private Integer age;

    @NotNull
    @DefaultValue(booleanValue = false)
    private Boolean isMarried;

    @NotNull
    @DefaultValue(intValue = 1000)
    private Integer pay;

    public UserSurvey() {
        super();
        this.fullName = "test";
        this.gender = "test";
        this.age = 18;
        this.isMarried = false;
        this.pay = 1000;

    }
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    public String getFullName() {
        return fullName;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getGender() {
        return gender;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public Integer getAge() {
        return age;
    }

    public void setIsMarried(Boolean isMarried) {
        this.isMarried = isMarried;
    }

    public Boolean getIsMarried() {
        return isMarried;
    }

    public void setPay(Integer pay) {
        this.pay = pay;
    }

    public Integer getPay() {
        return pay;
    }

}
